apps/articles/urls.py
from django.conf.urls import url

from .views import ArticlesView, ArticleView

urlpatterns = [
    url(r'^$', ArticlesView.as_view(), name='articles'),
    url(r'^(?P<article_id>\d+)/$', ArticleView.as_view()),
]

apps/home/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view()),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('apps.home.urls')),
    url(r'^articles/', include('apps.articles.urls', namespace='articles')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/articles/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField('Название категории', max_length=255)
    slug = models.SlugField('Alias категории', unique=True)
    parent_id = models.IntegerField('Родительская категории', default=0)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Articles(models.Model):
    name = models.CharField('Название статьи', max_length=255)
    create_date = models.DateField('Дата публикации')
    short_text = models.TextField('Аннотация статьи', default='')
    text = models.TextField('Текст статьи', default='')
    category_id = models.ForeignKey(Categories)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-create_date']

    def __str__(self):
        return self.name

apps/articles/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.utils import dateformat
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template.loader import render_to_string
from django.shortcuts import render
from django.views import View

from .models import Articles


class ArticlesView(View):
    articles = Articles.objects.all()

    def get(self, request):
        return render(request, 'articles/articles.html', {'articles': self.articles})


class ArticleView(View):
    def get(self, request, article_id):
        try:
            article = Articles.objects.get(id=article_id)
            return render(request, 'articles/article.html', {'article': article})
        except ObjectDoesNotExist:
            raise Http404

apps/home/views.py
from django.conf import settings
from django.utils import dateformat
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.shortcuts import render

from apps.articles.models import Articles
from apps.articles.views import ArticlesView


class HomeView(ArticlesView):
    def get(self, request):
        return render(request, 'home/home.html', {'articles': self.articles})

apps/articles/templates/articles/article.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
     <div class="article__item">
         <div class="row">
             <div class="col-xs-12">
                 <div class="page__goback">
                     <span class="glyphicon glyphicon-chevron-left glyphicon-big"></span>
                     <a href="{% url 'articles:articles' %}">К списку статей</a>
                 </div>
             </div>
         </div>
         <div class="row">
            <div class="col-xs-12">
                <h1 class="article__header">{{ article.name }}</h1>
                <p class="article__text">{{ article.text }}</p>
                <p class="article__date text-right">{{ article.create_date }}</p>
            </div>
         </div>
     </div>
    </div>
{% endblock %}

apps/articles/templates/articles/articles.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

     {% for article in articles %}
         <div class="article__item">
             <div class="row">
                <div class="col-xs-12">
                    <a href="{% url 'articles:articles' %}{{ article.id }}/" class="article__header">{{ article.name }}</a>
                    <p class="article__text">{{ article.short_text }}</p>
                    <p class="article__date text-right">{{ article.create_date }}</p>
                </div>
             </div>
         </div>
     {% endfor %}

    {{ data }}
    </div>
{% endblock %}

apps/home/templates/home/home.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

     {% for article in articles %}
         <div class="article__item">
             <div class="row">
                <div class="col-xs-12">
                    <a href="{% url 'articles:articles' %}{{ article.id }}/" class="article__header">{{ article.name }}</a>
                    <p class="article__text">{{ article.short_text }}</p>
                    <p class="article__date text-right">{{ article.create_date }}</p>
                </div>
             </div>
         </div>
     {% endfor %}

    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load compress %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Тестовый блог</title>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600&amp;subset=cyrillic" rel="stylesheet">

    {% compress css %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css'%}">
        <link type="text/less" rel="stylesheet" href="{% static 'less/common.less'%}">
    {% endcompress %}
</head>
<body>
<div class="wrapper">

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Блог Алексей Поселянина</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Статьи <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'articles:articles' %}">Все статьи</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">JavaScript</a></li>
                            <li><a href="#">Python</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}
</div>

{% compress js %}
    <script src="{% static 'jquery/dist/jquery.min.js'%}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js'%}"></script>
{% endcompress %}
</body>
</html>